name: Azure Static Web Apps

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main ]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Publish Blazor WASM
        working-directory: PlaylistConverter.Client
        run: dotnet publish -c Release -o ../client-build

      - name: Publish API
        working-directory: PlaylistConverter.Api
        run: dotnet publish -c Release -o ../api-build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          app_location: "PlaylistConverter.Client"          # repo folder (still required)
          output_location: "../client-build/wwwroot"        # PUBLISHED output
          api_location: "PlaylistConverter.Api"             # repo folder
          api_build_command: ""                             # we already published the API
          app_build_command: ""                             # we already published the app
          skip_api_build: true