name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ master ]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      # Let the SWA action run this build (kept for clarity), and publish to ./publish
      - name: Build Blazor WASM
        working-directory: PlaylistConverter.Client
        run: dotnet publish -c Release -o publish

      - name: Sanity check _framework exists
        run: ls -la PlaylistConverter.Client/publish/wwwroot/_framework

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_SKY_04E56E903 }}
          action: upload
          app_location: "PlaylistConverter.Client"
          output_location: "publish/wwwroot"          # IMPORTANT: published output
          # Remove api_location because you’re using an external App Service API.
          # If you keep it, it must be a Functions API. Otherwise omit.
          skip_api_build: true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: Azure/static-web-apps-deploy@v1
        with:
          action: close